token: mysecretjointoken
tls-san:
  - cp11
  - cp12
  - cp13
  - vagrantcluster
node-ip: 192.168.56.11
kube-apiserver-arg:
  - "oidc-client-id=081dc774-0f32-4e8e-9d35-a0a1bdcba90b"
  - "oidc-issuer-url=https://sts.windows.net/05e4a2de-78b6-410e-a14b-686a5ac65d61/"
  - "oidc-username-claim=email"
  - "oidc-groups-claim=groups"
